# -*- coding: utf-8 -*-
"""a in a word.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17PQvFgNNM5GrcPoZJs6-USL9IhR0IZOu
"""

def occur(str):
    count=0
    str=(input("Enter the string:"))
    char="a"
    for i in str:
        if (i==char):
            count+=1
    print("The letter a occured:",count,"times")
occur(str)