# -*- coding: utf-8 -*-
"""listoccursoo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLreCvz_rBT7y4ZVTsQ9KbgSfPeQW1L7
"""

li=[]
size=int(input("Enter the size of the list:"))
for i in range (0,size):  
     names=input("Enter the name with atleast one letter a:")
     li.append(names)
print("Your list is:",li)
def count_occur(li,size):
    count=0
    for i in li:                     #to count the no of words in list
        for j in i:                  #to count the no of a
            if(j=="a"):
                count=count+1
    return count 
print("a has occured",count_occur(li,size),"times.")